server:
  port: 8888
  servlet:
    context-path: /cacheTest
spring:
  redis:
    timeout: 6000
    host: 172.23.120.76
    port: 6379
    password: "issmart"
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    cluster:
#      max-redirects: 3 # 获取失败 最大重定向次数
#      nodes:
##        - 10.38.2.12:30379
#        - 172.23.123.141:7000
#        - 172.23.123.141:7001
#        - 172.23.123.141:7002
#        - 172.23.123.141:7003
#        - 172.23.123.141:7004
#        - 172.23.123.141:7005


  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    #mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
#  mvc:
#    static-path-pattern: static/**
#  freemarker:
#    template-loader-path: classpath:/templates/
#    cache: false
#    charset: utf-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .html