server:
  port: 8887
  servlet:
    context-path: /netcommand
spring:
  redis:
#    host: 10.38.2.12
#    port: 30013
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    password: 'issmart'

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    #mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
#  mvc:
#    static-path-pattern: static/**
#  freemarker:
#    template-loader-path: classpath:/templates/
#    cache: false
#    charset: utf-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .html